blog/urls.py
# url

from django.urls import path
from blog import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogs/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail-view'),
    path('blogs/bloggers/', views.AuthorListView.as_view(), name='bloggers'),
    path('blogs/bloggers/<int:pk>', views.AuthorDetailView.as_view(), name='author_detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('blogs/<int:pk>/create', views.comment_create, name='comment_create'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='/blog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import datetime
import uuid
# Create your models here.


# create model blog
class Author(models.Model):
    blogger_name = models.CharField(max_length=50)
    blogger_introduce = models.TextField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.blogger_name

    def get_absolute_url(self):
        return reverse('author_detail', args=[str(self.id)])


class Blog(models.Model):
    title = models.CharField(max_length=100, help_text="Write your blog title here")
    describe = models.TextField(max_length=3000, help_text="Write the text here")
    blog_write_time = models.DateTimeField(null=True, blank=True)
    blog_authors = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail-view', args=[str(self.id)])

    class Meta:
        ordering = ['blog_write_time']


class Comment(models.Model):
    comment_text = models.TextField(max_length=500, help_text="Weite your world here")
    comment_authors = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    comment_write_time = models.DateTimeField(null=True, blank=True)
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.comment_text

    def get_absolute_url(self):
        return reverse('blog-detail-view', args=[str(self.id)])

    class Meta:
        ordering = ['-comment_write_time']

    def display_commenttext(self):
        return self.comment_text[:15]
    display_commenttext.short_description = 'Comment'

blog/forms.py
from django.forms import ModelForm
from .models import Comment


class CreateCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text', ]

blog/views.py
from django.shortcuts import render
from .models import Author, Blog, Comment
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import CreateCommentForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
import datetime
# Create your views here.


def index(request):
    """
    View function for home page of site
    :param request:
    :return:
    """
    # create counts of objects
    num_blogs = Blog.objects.all().count()

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context={'num_blogs':num_blogs})


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BlogListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        return context


class BlogDetailView(generic.DetailView):
    model = Blog


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author


class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'


class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('')


from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


@login_required()
def comment_create(request, pk):
    blog_inst = get_object_or_404(Blog, pk=pk)

    # if this is a POST request then process the Form data
    if request.method == 'POST':

        # create a form comment and populate it with data from the request
        form = CreateCommentForm(request.POST)

        # check it if the form is valid
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()

            return HttpResponseRedirect(reverse('blog-detail-view', args=[pk]))
    else:
        form = CreateCommentForm(initial={'comment_text': 'Loin to comment'})

    return render(request, 'blog/comment_form.html', {'form': form, })



    

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Soft Blog</title>{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>


  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'blogs' %}">All Blogs</a></li>
          <li><a href="{% url 'bloggers' %}">All Bloggers</a></li>
      </ul>
          <dl>
          {% if user.is_authenticated %}
          <li>User:{{ user.get_username }}</li>
          <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a> </li>
          {% else %}
          <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a> </li>
          {% endif %}
          </dl>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

</body>
</html>

blog/templates/blog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Blogger</h1>

<p>Are you sure you want to delete the blogger: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

blog/templates/blog/author_detail.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>Blogger:{{ author.blogger_name }}</h1>
    <h3>Introduction:</h3>
    {% if author.blogger_introduce %}
        <p>{{ author.blogger_introduce }}</p>
    {% else %}
        <p>He is too lazy to write somethings</p>
    {% endif %}
    <h3>Blogs:</h3>
    {% for blog in author.blog_set.all %}
        <li><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>({{ blog.blog_write_time }}) </li>
    {% endfor %}
{% endblock %}

blog/templates/blog/author_form.html
{% extends "base_generic.html" %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    </form>
{% endblock %}

blog/templates/blog/author_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>Bloggers List</h1>
    {% if author_list %}
        {% for author in author_list %}
        <li><a href="{{ author.get_absolute_url }}">{{ author.blogger_name }}</a> </li>
        {% endfor %}
    {% else %}
        <p>Sorry,there is no blogger</p>
    {% endif %}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Title: {{ blog.title }}</h1>
    <p><strong>Author: {{ blog.blog_authors }}</strong></p>
    <p><strong>{{ blog.describe }}</strong></p>
    <h3>comment:</h3>
    <dl>
    {% for comment in blog.comment_set.all %}
        <a href="{{ comment.comment_authors.get_absolute_url }}">{{ comment.comment_authors }} </a> --({{ comment.comment_write_time }})
        <p>{{ comment.comment_text }}</p>
    {% endfor %}
    </dl>
    {% if user.is_authenticated %}
    <a href="{%  url 'comment_create' blog.id %}">Click here to comment</a>
    {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}">Login</a>to add comments
    {% endif %}
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Blog List</h1>
    {% if blog_list %}
        <ul>
        {% for blog in blog_list %}
        <li>
            <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>({{ blog.blog_write_time }})---
            <a href="{{ blog.blog_authors.get_absolute_url }}">{{ blog.blog_authors }}</a>
        </li>
        {% endfor %}
        </ul>
        {% else %}
        <p>There is no blog in soft blog</p>

    {% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>Blog:{{ comment.blog }}</h1>
    <form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit"/>
    </form>
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Soft Blog Home</h1>
    <p>Welcome to the soft blog</p>
    <h2>Blogs</h2>
    <p>The Soft Blog's Blog</p>
    <ul>
    <li><strong>Blogs:</strong>{{ num_blogs }}</li>
    </ul>

{% endblock %}